//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LambdaArchitecture.IntegrationTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeetupMessageTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeetupMessageTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LambdaArchitecture.IntegrationTests.MeetupMessageTemplate", typeof(MeetupMessageTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;venue&quot;: {
        ///    &quot;venue_name&quot;: &quot;Gates of Botanic Gardens, &quot;,
        ///    &quot;lon&quot;: -4.324862,
        ///    &quot;lat&quot;: 55.889885,
        ///    &quot;venue_id&quot;: 8380972
        ///  },
        ///  &quot;visibility&quot;: &quot;public&quot;,
        ///  &quot;response&quot;: &quot;yes&quot;,
        ///  &quot;guests&quot;: 0,
        ///  &quot;member&quot;: {
        ///    &quot;member_id&quot;: 99341612,
        ///    &quot;other_services&quot;: {
        ///      &quot;twitter&quot;: {
        ///        &quot;identifier&quot;: &quot;lexjah&quot;
        ///      },
        ///      &quot;flickr&quot;: {
        ///        &quot;identifier&quot;: &quot;http://www.flickr.com/photos/lexjah&quot;
        ///      },
        ///      &quot;facebook&quot;: {
        ///        &quot;identifier&quot;: &quot;https://www.facebook.com/app_scoped_user [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
    }
}
